"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ar" | "fr"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isRTL: boolean
}

const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.clients": "Clients",
    "nav.cases": "Cases",
    "nav.myCases": "My Cases",
    "nav.services": "Services",
    "nav.videoCalls": "Video Calls",
    "nav.messages": "Messages",
    "nav.settings": "Settings",
    "nav.appointments": "Appointments",
    "nav.documents": "Documents",
    "nav.billing": "Billing",
    "nav.profile": "Profile",
    "nav.analytics": "Analytics",
    "nav.subscription": "Subscription",

    // Common
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.export": "Export",
    "common.import": "Import",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.create": "Create",
    "common.submit": "Submit",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.open": "Open",
    "common.loading": "Loading",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.finish": "Finish",
    "common.start": "Start",
    "common.stop": "Stop",
    "common.pause": "Pause",
    "common.resume": "Resume",
    "common.retry": "Retry",
    "common.refresh": "Refresh",
    "common.logout": "Log out",
    "common.login": "Log in",
    "common.register": "Register",
    "common.notifications": "Notifications",
    "common.total": "Total",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.cancelled": "Cancelled",
    "common.draft": "Draft",
    "common.published": "Published",
    "common.archived": "Archived",

    // Time
    "time.minute": "minute",
    "time.minutes": "minutes",
    "time.hour": "hour",
    "time.hours": "hours",
    "time.day": "day",
    "time.days": "days",
    "time.week": "week",
    "time.weeks": "weeks",
    "time.month": "month",
    "time.months": "months",
    "time.year": "year",
    "time.years": "years",
    "time.ago": "ago",
    "time.fromNow": "from now",
    "time.today": "Today",
    "time.yesterday": "Yesterday",
    "time.tomorrow": "Tomorrow",

    // Status
    "status.new": "New",
    "status.inProgress": "In Progress",
    "status.review": "Under Review",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.closed": "Closed",
    "status.open": "Open",
    "status.resolved": "Resolved",
    "status.urgent": "Urgent",
    "status.high": "High Priority",
    "status.medium": "Medium Priority",
    "status.low": "Low Priority",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Here's what's happening with your cases today",
    "dashboard.totalCases": "Total Cases",
    "dashboard.activeCases": "Active Cases",
    "dashboard.completedCases": "Completed Cases",
    "dashboard.upcomingAppointments": "Upcoming Appointments",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.caseUpdates": "Case Updates",
    "dashboard.documentsToReview": "Documents to Review",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.nextCallIn": "Next call in 30 mins",
    "dashboard.requireAttention": "require attention",
    "dashboard.allSigned": "All signed",
    "dashboard.settlementPending": "Settlement pending",
    "dashboard.hoursAgo": "2 hours ago",

    // Video Calls
    "videoCalls.title": "Video Calls",
    "videoCalls.upcoming": "Upcoming Calls",
    "videoCalls.history": "Call History",
    "videoCalls.schedule": "Schedule Call",
    "videoCalls.join": "Join Call",
    "videoCalls.start": "Start Call",
    "videoCalls.end": "End Call",
    "videoCalls.mute": "Mute",
    "videoCalls.unmute": "Unmute",
    "videoCalls.camera": "Camera",
    "videoCalls.cameraOff": "Camera Off",
    "videoCalls.screenShare": "Share Screen",
    "videoCalls.stopSharing": "Stop Sharing",
    "videoCalls.chat": "Chat",
    "videoCalls.participants": "Participants",
    "videoCalls.record": "Record",
    "videoCalls.stopRecording": "Stop Recording",
    "videoCalls.callDuration": "Call Duration",
    "videoCalls.connecting": "Connecting...",
    "videoCalls.connected": "Connected",
    "videoCalls.disconnected": "Disconnected",
    "videoCalls.reconnecting": "Reconnecting...",
    "videoCalls.callEnded": "Call Ended",
    "videoCalls.noUpcoming": "No upcoming video calls",
    "videoCalls.scheduleFirst": "Schedule your first consultation",
    "videoCalls.consultationWith": "Consultation with",
    "videoCalls.duration": "Duration",
    "videoCalls.status": "Status",
    "videoCalls.scheduled": "Scheduled",
    "videoCalls.inProgress": "In Progress",
    "videoCalls.completed": "Completed",
    "videoCalls.missed": "Missed",
    "videoCalls.rescheduled": "Rescheduled",
    "videoCalls.waitingRoom": "Waiting Room",
    "videoCalls.lawyerWillJoin": "Your lawyer will join shortly",
    "videoCalls.testConnection": "Test Connection",
    "videoCalls.checkAudio": "Check Audio & Video",
    "videoCalls.callQuality": "Call Quality",
    "videoCalls.excellent": "Excellent",
    "videoCalls.good": "Good",
    "videoCalls.poor": "Poor",

    // Subscription
    "subscription.title": "Subscription Plans",
    "subscription.current": "Current Plan",
    "subscription.upgrade": "Upgrade Plan",
    "subscription.downgrade": "Downgrade Plan",
    "subscription.cancel": "Cancel Subscription",
    "subscription.renew": "Renew Subscription",
    "subscription.billing": "Billing Information",
    "subscription.nextBilling": "Next Billing Date",
    "subscription.paymentMethod": "Payment Method",
    "subscription.invoiceHistory": "Invoice History",
    "subscription.mostPopular": "Most Popular",
    "subscription.basic": "Basic",
    "subscription.premium": "Premium",
    "subscription.enterprise": "Enterprise",
    "subscription.perMonth": "per month",
    "subscription.perYear": "per year",
    "subscription.billed": "billed",
    "subscription.monthly": "monthly",
    "subscription.annually": "annually",
    "subscription.features": "Features",
    "subscription.unlimited": "Unlimited",
    "subscription.limited": "Limited",
    "subscription.support": "Support",
    "subscription.priority": "Priority",
    "subscription.standard": "Standard",
    "subscription.advanced": "Advanced",

    // UI Elements
    "ui.toggleNavigation": "Toggle navigation menu",
    "ui.searchCasesDocuments": "Search cases, documents...",
    "ui.userAvatar": "User Avatar",
    "ui.selectLanguage": "Select Language",
    "ui.english": "English",
    "ui.arabic": "العربية",
    "ui.french": "Français",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.clients": "العملاء",
    "nav.cases": "القضايا",
    "nav.myCases": "قضاياي",
    "nav.services": "الخدمات",
    "nav.videoCalls": "المكالمات المرئية",
    "nav.messages": "الرسائل",
    "nav.settings": "الإعدادات",
    "nav.appointments": "المواعيد",
    "nav.documents": "المستندات",
    "nav.billing": "الفواتير",
    "nav.profile": "الملف الشخصي",
    "nav.analytics": "التحليلات",
    "nav.subscription": "الاشتراك",

    // Common
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.export": "تصدير",
    "common.import": "استيراد",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.add": "إضافة",
    "common.remove": "إزالة",
    "common.update": "تحديث",
    "common.create": "إنشاء",
    "common.submit": "إرسال",
    "common.confirm": "تأكيد",
    "common.close": "إغلاق",
    "common.open": "فتح",
    "common.loading": "جاري التحميل",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.warning": "تحذير",
    "common.info": "معلومات",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.ok": "موافق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.finish": "إنهاء",
    "common.start": "بدء",
    "common.stop": "إيقاف",
    "common.pause": "إيقاف مؤقت",
    "common.resume": "استئناف",
    "common.retry": "إعادة المحاولة",
    "common.refresh": "تحديث",
    "common.logout": "تسجيل الخروج",
    "common.login": "تسجيل الدخول",
    "common.register": "التسجيل",
    "common.notifications": "الإشعارات",
    "common.total": "المجموع",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.pending": "معلق",
    "common.completed": "مكتمل",
    "common.cancelled": "ملغي",
    "common.draft": "مسودة",
    "common.published": "منشور",
    "common.archived": "مؤرشف",

    // Time
    "time.minute": "دقيقة",
    "time.minutes": "دقائق",
    "time.hour": "ساعة",
    "time.hours": "ساعات",
    "time.day": "يوم",
    "time.days": "أيام",
    "time.week": "أسبوع",
    "time.weeks": "أسابيع",
    "time.month": "شهر",
    "time.months": "أشهر",
    "time.year": "سنة",
    "time.years": "سنوات",
    "time.ago": "منذ",
    "time.fromNow": "من الآن",
    "time.today": "اليوم",
    "time.yesterday": "أمس",
    "time.tomorrow": "غداً",

    // Status
    "status.new": "جديد",
    "status.inProgress": "قيد التنفيذ",
    "status.review": "قيد المراجعة",
    "status.approved": "موافق عليه",
    "status.rejected": "مرفوض",
    "status.closed": "مغلق",
    "status.open": "مفتوح",
    "status.resolved": "محلول",
    "status.urgent": "عاجل",
    "status.high": "أولوية عالية",
    "status.medium": "أولوية متوسطة",
    "status.low": "أولوية منخفضة",

    // Dashboard
    "dashboard.welcome": "مرحباً بعودتك",
    "dashboard.overview": "إليك ما يحدث مع قضاياك اليوم",
    "dashboard.totalCases": "إجمالي القضايا",
    "dashboard.activeCases": "القضايا النشطة",
    "dashboard.completedCases": "القضايا المكتملة",
    "dashboard.upcomingAppointments": "المواعيد القادمة",
    "dashboard.recentActivity": "النشاط الأخير",
    "dashboard.quickActions": "إجراءات سريعة",
    "dashboard.caseUpdates": "تحديثات القضايا",
    "dashboard.documentsToReview": "مستندات للمراجعة",
    "dashboard.fromLastMonth": "من الشهر الماضي",
    "dashboard.nextCallIn": "المكالمة التالية خلال 30 دقيقة",
    "dashboard.requireAttention": "تتطلب انتباه",
    "dashboard.allSigned": "جميعها موقعة",
    "dashboard.settlementPending": "التسوية معلقة",
    "dashboard.hoursAgo": "منذ ساعتين",

    // Video Calls
    "videoCalls.title": "المكالمات المرئية",
    "videoCalls.upcoming": "المكالمات القادمة",
    "videoCalls.history": "سجل المكالمات",
    "videoCalls.schedule": "جدولة مكالمة",
    "videoCalls.join": "انضمام للمكالمة",
    "videoCalls.start": "بدء المكالمة",
    "videoCalls.end": "إنهاء المكالمة",
    "videoCalls.mute": "كتم الصوت",
    "videoCalls.unmute": "إلغاء كتم الصوت",
    "videoCalls.camera": "الكاميرا",
    "videoCalls.cameraOff": "إيقاف الكاميرا",
    "videoCalls.screenShare": "مشاركة الشاشة",
    "videoCalls.stopSharing": "إيقاف المشاركة",
    "videoCalls.chat": "المحادثة",
    "videoCalls.participants": "المشاركون",
    "videoCalls.record": "تسجيل",
    "videoCalls.stopRecording": "إيقاف التسجيل",
    "videoCalls.callDuration": "مدة المكالمة",
    "videoCalls.connecting": "جاري الاتصال...",
    "videoCalls.connected": "متصل",
    "videoCalls.disconnected": "منقطع",
    "videoCalls.reconnecting": "جاري إعادة الاتصال...",
    "videoCalls.callEnded": "انتهت المكالمة",
    "videoCalls.noUpcoming": "لا توجد مكالمات مرئية قادمة",
    "videoCalls.scheduleFirst": "جدول استشارتك الأولى",
    "videoCalls.consultationWith": "استشارة مع",
    "videoCalls.duration": "المدة",
    "videoCalls.status": "الحالة",
    "videoCalls.scheduled": "مجدولة",
    "videoCalls.inProgress": "قيد التنفيذ",
    "videoCalls.completed": "مكتملة",
    "videoCalls.missed": "فائتة",
    "videoCalls.rescheduled": "معاد جدولتها",
    "videoCalls.waitingRoom": "غرفة الانتظار",
    "videoCalls.lawyerWillJoin": "سينضم محاميك قريباً",
    "videoCalls.testConnection": "اختبار الاتصال",
    "videoCalls.checkAudio": "فحص الصوت والفيديو",
    "videoCalls.callQuality": "جودة المكالمة",
    "videoCalls.excellent": "ممتازة",
    "videoCalls.good": "جيدة",
    "videoCalls.poor": "ضعيفة",

    // Subscription
    "subscription.title": "خطط الاشتراك",
    "subscription.current": "الخطة الحالية",
    "subscription.upgrade": "ترقية الخطة",
    "subscription.downgrade": "تخفيض الخطة",
    "subscription.cancel": "إلغاء الاشتراك",
    "subscription.renew": "تجديد الاشتراك",
    "subscription.billing": "معلومات الفواتير",
    "subscription.nextBilling": "تاريخ الفاتورة التالية",
    "subscription.paymentMethod": "طريقة الدفع",
    "subscription.invoiceHistory": "سجل الفواتير",
    "subscription.mostPopular": "الأكثر شعبية",
    "subscription.basic": "أساسي",
    "subscription.premium": "مميز",
    "subscription.enterprise": "مؤسسي",
    "subscription.perMonth": "شهرياً",
    "subscription.perYear": "سنوياً",
    "subscription.billed": "يُحاسب",
    "subscription.monthly": "شهرياً",
    "subscription.annually": "سنوياً",
    "subscription.features": "المميزات",
    "subscription.unlimited": "غير محدود",
    "subscription.limited": "محدود",
    "subscription.support": "الدعم",
    "subscription.priority": "أولوية",
    "subscription.standard": "قياسي",
    "subscription.advanced": "متقدم",

    // UI Elements
    "ui.toggleNavigation": "تبديل قائمة التنقل",
    "ui.searchCasesDocuments": "البحث في القضايا والمستندات...",
    "ui.userAvatar": "صورة المستخدم",
    "ui.selectLanguage": "اختر اللغة",
    "ui.english": "English",
    "ui.arabic": "العربية",
    "ui.french": "Français",
  },
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.clients": "Clients",
    "nav.cases": "Affaires",
    "nav.myCases": "Mes Affaires",
    "nav.services": "Services",
    "nav.videoCalls": "Appels vidéo",
    "nav.messages": "Messages",
    "nav.settings": "Paramètres",
    "nav.appointments": "Rendez-vous",
    "nav.documents": "Documents",
    "nav.billing": "Facturation",
    "nav.profile": "Profil",
    "nav.analytics": "Analyses",
    "nav.subscription": "Abonnement",

    // Common
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.export": "Exporter",
    "common.import": "Importer",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.view": "Voir",
    "common.add": "Ajouter",
    "common.remove": "Retirer",
    "common.update": "Mettre à jour",
    "common.create": "Créer",
    "common.submit": "Soumettre",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",
    "common.open": "Ouvrir",
    "common.loading": "Chargement",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.warning": "Avertissement",
    "common.info": "Information",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.ok": "OK",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.finish": "Terminer",
    "common.start": "Commencer",
    "common.stop": "Arrêter",
    "common.pause": "Pause",
    "common.resume": "Reprendre",
    "common.retry": "Réessayer",
    "common.refresh": "Actualiser",
    "common.logout": "Se déconnecter",
    "common.login": "Se connecter",
    "common.register": "S'inscrire",
    "common.notifications": "Notifications",
    "common.total": "Total",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.pending": "En attente",
    "common.completed": "Terminé",
    "common.cancelled": "Annulé",
    "common.draft": "Brouillon",
    "common.published": "Publié",
    "common.archived": "Archivé",

    // Time
    "time.minute": "minute",
    "time.minutes": "minutes",
    "time.hour": "heure",
    "time.hours": "heures",
    "time.day": "jour",
    "time.days": "jours",
    "time.week": "semaine",
    "time.weeks": "semaines",
    "time.month": "mois",
    "time.months": "mois",
    "time.year": "année",
    "time.years": "années",
    "time.ago": "il y a",
    "time.fromNow": "dans",
    "time.today": "Aujourd'hui",
    "time.yesterday": "Hier",
    "time.tomorrow": "Demain",

    // Status
    "status.new": "Nouveau",
    "status.inProgress": "En cours",
    "status.review": "En révision",
    "status.approved": "Approuvé",
    "status.rejected": "Rejeté",
    "status.closed": "Fermé",
    "status.open": "Ouvert",
    "status.resolved": "Résolu",
    "status.urgent": "Urgent",
    "status.high": "Priorité élevée",
    "status.medium": "Priorité moyenne",
    "status.low": "Priorité faible",

    // Dashboard
    "dashboard.welcome": "Bon retour",
    "dashboard.overview": "Voici ce qui se passe avec vos affaires aujourd'hui",
    "dashboard.totalCases": "Total des Affaires",
    "dashboard.activeCases": "Affaires Actives",
    "dashboard.completedCases": "Affaires Terminées",
    "dashboard.upcomingAppointments": "Rendez-vous à venir",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.caseUpdates": "Mises à jour des affaires",
    "dashboard.documentsToReview": "Documents à réviser",
    "dashboard.fromLastMonth": "du mois dernier",
    "dashboard.nextCallIn": "Prochain appel dans 30 min",
    "dashboard.requireAttention": "nécessitent une attention",
    "dashboard.allSigned": "Tous signés",
    "dashboard.settlementPending": "Règlement en attente",
    "dashboard.hoursAgo": "Il y a 2 heures",

    // Video Calls
    "videoCalls.title": "Appels vidéo",
    "videoCalls.upcoming": "Appels à venir",
    "videoCalls.history": "Historique des appels",
    "videoCalls.schedule": "Planifier un appel",
    "videoCalls.join": "Rejoindre l'appel",
    "videoCalls.start": "Démarrer l'appel",
    "videoCalls.end": "Terminer l'appel",
    "videoCalls.mute": "Couper le son",
    "videoCalls.unmute": "Activer le son",
    "videoCalls.camera": "Caméra",
    "videoCalls.cameraOff": "Caméra éteinte",
    "videoCalls.screenShare": "Partager l'écran",
    "videoCalls.stopSharing": "Arrêter le partage",
    "videoCalls.chat": "Chat",
    "videoCalls.participants": "Participants",
    "videoCalls.record": "Enregistrer",
    "videoCalls.stopRecording": "Arrêter l'enregistrement",
    "videoCalls.callDuration": "Durée de l'appel",
    "videoCalls.connecting": "Connexion...",
    "videoCalls.connected": "Connecté",
    "videoCalls.disconnected": "Déconnecté",
    "videoCalls.reconnecting": "Reconnexion...",
    "videoCalls.callEnded": "Appel terminé",
    "videoCalls.noUpcoming": "Aucun appel vidéo à venir",
    "videoCalls.scheduleFirst": "Planifiez votre première consultation",
    "videoCalls.consultationWith": "Consultation avec",
    "videoCalls.duration": "Durée",
    "videoCalls.status": "Statut",
    "videoCalls.scheduled": "Planifié",
    "videoCalls.inProgress": "En cours",
    "videoCalls.completed": "Terminé",
    "videoCalls.missed": "Manqué",
    "videoCalls.rescheduled": "Reprogrammé",
    "videoCalls.waitingRoom": "Salle d'attente",
    "videoCalls.lawyerWillJoin": "Votre avocat vous rejoindra bientôt",
    "videoCalls.testConnection": "Tester la connexion",
    "videoCalls.checkAudio": "Vérifier l'audio et la vidéo",
    "videoCalls.callQuality": "Qualité de l'appel",
    "videoCalls.excellent": "Excellente",
    "videoCalls.good": "Bonne",
    "videoCalls.poor": "Faible",

    // Subscription
    "subscription.title": "Plans d'abonnement",
    "subscription.current": "Plan actuel",
    "subscription.upgrade": "Mettre à niveau",
    "subscription.downgrade": "Rétrograder",
    "subscription.cancel": "Annuler l'abonnement",
    "subscription.renew": "Renouveler l'abonnement",
    "subscription.billing": "Informations de facturation",
    "subscription.nextBilling": "Prochaine date de facturation",
    "subscription.paymentMethod": "Méthode de paiement",
    "subscription.invoiceHistory": "Historique des factures",
    "subscription.mostPopular": "Le plus populaire",
    "subscription.basic": "Basique",
    "subscription.premium": "Premium",
    "subscription.enterprise": "Entreprise",
    "subscription.perMonth": "par mois",
    "subscription.perYear": "par an",
    "subscription.billed": "facturé",
    "subscription.monthly": "mensuellement",
    "subscription.annually": "annuellement",
    "subscription.features": "Fonctionnalités",
    "subscription.unlimited": "Illimité",
    "subscription.limited": "Limité",
    "subscription.support": "Support",
    "subscription.priority": "Priorité",
    "subscription.standard": "Standard",
    "subscription.advanced": "Avancé",

    // UI Elements
    "ui.toggleNavigation": "Basculer le menu de navigation",
    "ui.searchCasesDocuments": "Rechercher affaires, documents...",
    "ui.userAvatar": "Avatar utilisateur",
    "ui.selectLanguage": "Sélectionner la langue",
    "ui.english": "English",
    "ui.arabic": "العربية",
    "ui.french": "Français",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ar", "fr"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.lang = language
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr"
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  const isRTL = language === "ar"

  return <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
